
import React, { useState } from 'react';
import { generateRoadmap } from '../services/geminiService';
import type { RoadmapMilestone, Page, User } from '../types';
import { Loader2, Feather, CheckSquare, FileText, Sparkles } from 'lucide-react';

interface RoadmapGeneratorProps {
  onNavClick: (page: Page) => void;
  user: User;
}

const RoadmapGenerator: React.FC<RoadmapGeneratorProps> = ({ user }) => {
  const [goal, setGoal] = useState('');
  const [roadmap, setRoadmap] = useState<RoadmapMilestone[] | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [completedSteps, setCompletedSteps] = useState<Set<number>>(new Set());

  const handleGenerate = async () => {
    if (!goal.trim()) return setError('Please enter a learning goal.');
    setIsLoading(true);
    setError(null);
    try {
      const result = await generateRoadmap(goal);
      setRoadmap(result);
    } catch (err: any) {
      setError(err.message || 'Error occurred.');
    } finally {
      setIsLoading(false);
    }
  };

  const exportAsMarkdown = () => {
    if (!roadmap) return;
    let md = `# Learning Roadmap: ${goal}\n\n`;
    md += `**Student:** ${user.name}\n`;
    md += `**Date:** ${new Date().toLocaleDateString()}\n\n`;
    md += `---\n\n`;
    roadmap.forEach(m => {
      md += `## Week ${m.week}: ${m.title}\n`;
      md += `${m.description}\n\n`;
      md += `### Resources & Projects:\n`;
      m.resources.forEach(r => md += `- [ ] ${r}\n`);
      md += `\n`;
    });
    md += `---\nGenerated by LearnStackHub AI`;
    
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${goal.replace(/\s+/g, '-').toLowerCase()}-roadmap.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container mx-auto px-6 py-12">
      <div className="max-w-3xl mx-auto text-center no-print">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-cyan-500/10 rounded-full text-cyan-400 text-xs font-bold mb-4 border border-cyan-500/20">
          <Sparkles size={14} /> AI POWERED CURRICULUM
        </div>
        <h1 className="text-4xl md:text-5xl font-black mb-2 font-montserrat tracking-tight text-white">Roadmap Architect</h1>
        <p className="text-slate-400 mb-8">Tell us your goal, and our AI will build a personalized path for you.</p>
        <div className="flex flex-col sm:flex-row gap-4 bg-slate-900/60 p-2 rounded-3xl border border-slate-700/50 shadow-2xl">
          <input 
            type="text" 
            value={goal} 
            onChange={e => setGoal(e.target.value)} 
            placeholder="e.g., 'Master Machine Learning with Python'" 
            className="flex-grow bg-transparent px-6 text-gray-200 focus:outline-none py-3" 
          />
          <button onClick={handleGenerate} disabled={isLoading} className="px-10 py-3 bg-gradient-to-r from-cyan-600 to-blue-600 text-white font-black rounded-2xl transition-all hover:scale-105 disabled:opacity-50 shadow-lg shadow-cyan-900/20">
            {isLoading ? <Loader2 className="animate-spin" /> : 'Generate My Path'}
          </button>
        </div>
        {error && <p className="mt-4 text-red-400 font-bold">{error}</p>}
      </div>

      {roadmap && (
        <div className="mt-12 max-w-4xl mx-auto animate-fade-in">
          <div className="flex justify-between items-center mb-8 no-print">
            <h2 className="text-2xl font-black text-white font-montserrat tracking-tight">Your Custom Path</h2>
            <div className="flex gap-4">
               <button onClick={exportAsMarkdown} className="flex items-center gap-2 px-6 py-3 bg-slate-800 text-slate-200 font-bold rounded-2xl border border-slate-700 transition-all hover:bg-slate-700">
                  <FileText size={20} /> Download Markdown (.md)
               </button>
            </div>
          </div>
          <div className="space-y-8 relative pl-8 border-l-2 border-slate-700/50">
            {roadmap.map(m => (
              <div key={m.week} className="relative roadmap-milestone">
                <div className={`absolute -left-[3.1rem] top-0 w-12 h-12 rounded-2xl flex items-center justify-center text-white font-black shadow-xl no-print ${completedSteps.has(m.week) ? 'bg-green-500' : 'bg-slate-700'}`}>
                  {completedSteps.has(m.week) ? <CheckSquare size={24} /> : m.week}
                </div>
                <div className="bg-slate-900/40 border border-slate-700/50 rounded-3xl p-8 shadow-2xl backdrop-blur-md">
                  <h3 className="text-2xl font-black text-slate-100 mb-2">{m.title}</h3>
                  <p className="text-slate-400 mb-6 leading-relaxed">{m.description}</p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {m.resources.map((r, i) => (
                      <div key={i} className="flex items-start gap-3 text-sm text-slate-300 bg-slate-800/30 p-4 rounded-2xl border border-slate-700/30">
                        <Feather size={16} className="text-cyan-400 mt-0.5" /><span>{r}</span>
                      </div>
                    ))}
                  </div>
                  <button onClick={() => setCompletedSteps(prev => {const s = new Set(prev); s.has(m.week) ? s.delete(m.week) : s.add(m.week); return s;})} className="mt-6 text-[10px] font-black text-slate-500 hover:text-cyan-400 no-print uppercase tracking-widest transition-colors">
                    {completedSteps.has(m.week) ? 'Mark Week Incomplete' : 'Mark Week as Mastered'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default RoadmapGenerator;
